---
- name: Ensure python requests library is installed
  ansible.builtin.pip:
    name:
      - requests
      - pyOpenSSL
      - paramiko
  delegate_to: localhost

- name: Login to Docker Hub
  community.docker.docker_login:
    registry_url: https://index.docker.io/v1/
    username: "{{ docker_hub_username }}"
    password: "{{ docker_hub_password }}"
  delegate_to: localhost

- name: Build an image and push it to a private repo
  community.docker.docker_image:
    build:
      path: "{{ item.dir }}"
      nocache: true
      args: "{{ item.darg }}"
    name: incept1on/hcalendar
    tag: "{{ item.dtag }}"
    push: true
    source: build
    force_source: true
  loop: "{{ images }}"
  delegate_to: localhost
  changed_when: true
