- name: Build and push to dockerhub the image
  hosts: all
  tasks:
    - name: Install docker
      ansible.builtin.import_role:
        name: installDocker
      become: true

    - name: Build and push images to dockerhub
      ansible.builtin.import_role:
        name: buildDockerImage
