name: Build and push files to the dockerhub

on: 
  workflow_dispatch:
  push:
  pull_request:


jobs:
  some:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Change the ip in the inventory like in vars
        run: |
          sed 's/ansible_host:.*$/ansible_host: ${{vars.ANSIBLE_HOST}}/' ./Ansible/inventory.yml

      - name: Create pass file in Ansible folder
        run: |
          echo ${{secrets.VAULT_PASSWORD}} > ./Ansible/pass.txt
    
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Run ansible playbook buildAndPush.ansible.yml
        run: |
          ansible-playbook ./Ansible/buildAndPush.ansible.yml -i ./Ansible/inventory.yml --vault-pass-file ./Ansible/pass.txt --ssh-extra-args='-o StrictHostKeyChecking=no'
          
      - name: Run ansible playbook pullDockerComposeAndRun.ansible.yml
        run: |
          ansible-playbook ./Ansible/pullDockerComposeAndRun.ansible.yml -i ./Ansible/inventory.yml --ssh-extra-args='-o StrictHostKeyChecking=no'
